name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MARGPROJEKTERKEA }}
          name: id_rsa # optional
          known hosts: ${{ secrets.SSH_HOST }}
          config: ${{ secrets.CONFIG }} # ssh config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          
      - name: Pull
        run: ssh git-user@1.1.1.1 "cd /var/www/html/&& /usr/bin/git pull origin staging'
