name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1

#      - run: npm install
#      - run: npm run build

    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build
#
#      - name: Run tests
#        run: npm run test
#
#      - name: Upload production-ready build files
#        uses: actions/upload-artifact@v2
#        with:
#          name: production-files
#          path: ./dist



  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home/projekterkea/www/keaprodukter
        remote_host: kea.dk
        remote_user: projekterkea
        remote_key: "${{ secrets.MARGPROJEKTERKEA }}"

#  deploy:
#    name: Deploy
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'

#    steps:
#      - name: Install SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{secrets.MARGPROJEKTERKEA}}
#          known_hosts: ${{secrets.MARGPROJEKTERKEA_HOST}}
          
#      - name: Deploy with rsync
#        run: rsync -avz ./dist/* projekterkea@kea.dk:/home/projekterkea/www/keaprodukter

        
